/-
  PolicyEnv.AuditBound — S4-D-13, hardened by S4-D-30 (sprint v4)

  Decidable Tier 1–2 predicate for the enforced audit bound on EDC
  write-corrections. The proxy calls verify with a typed `AuditEntry` +
  `VerifyContext` (see `PolicyEnv.Contract`); the kernel checks
  `AuditEntryValid` and the proxy forwards to the EDC only on PROVED.

  S4-D-30 acceptance properties, checked at compile time below:
  * PROVED on an entry chained to the CURRENT HEAD of a real Merkle-chain
    ledger fixture (numbers derived from `scripts/fixtures/audit_ledger/`,
    generated by biject-api's own chain code; agreement is re-checked at
    runtime by `scripts/audit_bound_harness.py`);
  * REFUTED on backdated, future-skewed, invalid-sig, missing-reason, and
    unknown-reason-code entries — five distinct vectors;
  * REFUTED on stub-shaped ledger-head contexts (non-digest head hash,
    genesis/timestamp inconsistency in either direction).

  House rules: no `sorry`, no `axiom`, no `native_decide`, no `unsafe`,
  no `extern`. All checks are Nat comparisons, String (in)equality, String
  length, enum bounds, and one Bool equation — nothing that can time out
  `decide`.
-/
import PolicyEnv.Contract

namespace PolicyEnv

open Contract

/--
  The enforced audit bound. An entry is valid against the current ledger
  head and proxy clock iff ALL of:

  1.  actor present — `actorId` non-empty;
  2.  target present — `itemOid` non-empty;
  3.  action code in enum range;
  4.  reason PRESENT — `reasonCode ≠ none` (a wire body with no reason field
      is refuted here even if the extraction boundary ever regressed);
  5.  reason code in enum range — `getD reasonCodeCount` makes the missing
      case fail this clause too (the default is deliberately out of range),
      so 4 and 5 are distinct refutations that both fail closed;
  6.  ledger head well-formed — `ledgerHeadHash` has sha256-hex length
      (64 bytes; hex digests are pure ASCII so UTF-8 byte length IS the
      character length — `utf8ByteSize` is used because it is axiom-free
      in this toolchain where `String.length` is not; a stub context like
      `""` or `"stub"` cannot pose as a chain head);
  7.  genesis consistency, forward — a genesis head means an empty chain,
      so its timestamp must be 0;
  8.  genesis consistency, backward — a zero head timestamp is only the
      empty chain, so the head must be the genesis sentinel (a zeroed
      timestamp stub alongside a real head hash is refuted);
  9.  not backdated — timestamp STRICTLY greater than the ledger head
      (`ledgerHeadTsMs < tsUnixMs`; an entry stamped exactly at the head is
      a replay, not a successor — no off-by-one here is deliberate);
  10. within the forward skew window — `tsUnixMs ≤ nowMs + forwardSkewMs`
      (`nowMs` is the trusted proxy clock, see `Contract`);
  11. signature verified — `sigOk = true` (trusted verdict: Ed25519 over
      the signed digest recomputed from the ledger-stored canonical params,
      see `Contract`);
  12. hashes bound — a `modify` must actually change the value
      (`oldValueHash ≠ newValueHash`), and
  13. a `modify` must have had a prior value (`oldValueHash ≠ ""`).

  Every field of `AuditEntry` and `VerifyContext` is consumed by some
  clause: `itemOid` (2), `actorId` (1), `action` (3, 12, 13),
  `reasonCode` (4, 5), `tsUnixMs` (9, 10), `oldValueHash`/`newValueHash`
  (12, 13), `sigOk` (11), `ledgerHeadHash` (6, 7, 8), `ledgerHeadTsMs`
  (7, 8, 9), `nowMs` (10).
-/
def AuditEntryValid (e : AuditEntry) (ctx : VerifyContext) : Prop :=
  e.actorId ≠ ""
  ∧ e.itemOid ≠ ""
  ∧ e.action < actionCount
  ∧ e.reasonCode ≠ none
  ∧ e.reasonCode.getD reasonCodeCount < reasonCodeCount
  ∧ ctx.ledgerHeadHash.utf8ByteSize = digestHexLength
  ∧ (ctx.ledgerHeadHash = genesisHeadHash → ctx.ledgerHeadTsMs = 0)
  ∧ (ctx.ledgerHeadTsMs = 0 → ctx.ledgerHeadHash = genesisHeadHash)
  ∧ ctx.ledgerHeadTsMs < e.tsUnixMs
  ∧ e.tsUnixMs ≤ ctx.nowMs + forwardSkewMs
  ∧ e.sigOk = true
  ∧ (e.action = actionModify → e.oldValueHash ≠ e.newValueHash)
  ∧ (e.action = actionModify → e.oldValueHash ≠ "")

/--
  Decidability: the predicate is a finite conjunction of decidable atoms
  (Nat `<`/`≤`/`=`, String/Option `≠`, Bool `=`, and implications between
  them), so the instance derives by instance search alone — no classical
  axioms.
-/
instance instDecidableAuditEntryValid (e : AuditEntry) (ctx : VerifyContext) :
    Decidable (AuditEntryValid e ctx) := by
  unfold AuditEntryValid
  infer_instance

/-! ## Compile-time regression vectors

`lake build` fails if any of these stops holding. All proofs are by
`decide` — plain kernel evaluation, never `native_decide`.

### Where the accepting numbers come from (S4-D-30)

The context and entry below are chained to the CURRENT HEAD of the golden
ledger fixture `scripts/fixtures/audit_ledger/audit.log` — three PROVED
write-corrections appended by biject-api's real chain code
(`backend/app/audit.py::_append_audit`, driven by
`scripts/gen_audit_fixture.py`):

* `fixtureHeadHash`   = the head entry's `entry_hash` (line 3 of the
                        fixture; also `chain_head_hash` in the fixture's
                        `audit_head.json` head pointer);
* `ledgerHeadTsMs`    = 1755400000355
                      = max(head `params.ts_unix_ms` = 1755400000300,
                            head `timestamp_ns / 10^6` = 1755400000355) —
                        the stricter of the head's claimed and recorded
                        times;
* `oldValueHash`      = the head entry's `params.new_value_hash`
                      = sha256("1.2") — the candidate corrects the exact
                        value the chain last committed for `I_LABS_CREAT`;
* `newValueHash`      = sha256("1.25") — the corrected value;
* `tsUnixMs` / `nowMs` postdate the head by 545/645 ms, inside the 5000 ms
  skew window.

`scripts/audit_bound_harness.py` re-derives every one of these values from
the fixture at runtime (after full chain verification: canonical-hash
recompute, prev-hash linkage, Ed25519 over `entry_hash`, head-pointer
cross-check) and fails if this file and the fixture ever disagree.
-/

/-- `entry_hash` of the fixture chain head (see the provenance note above). -/
private def fixtureHeadHash : String :=
  "d6eda262aad8f1e047f354f94666a02423e4c9da40a41f0aa25ef725b5fb08e8"

/-- The real-ledger context: verified fixture head, proxy clock 645 ms past it. -/
private def ctx0 : VerifyContext :=
  { ledgerHeadHash := fixtureHeadHash
    ledgerHeadTsMs := 1755400000355
    nowMs := 1755400001000 }

/-- A well-formed transcription-error correction of the value the fixture
head committed (`"1.2"` → `"1.25"`), 545 ms after the ledger head. -/
private def validEntry : AuditEntry :=
  { itemOid := "I_LABS_CREAT"
    actorId := "AGENT_RECONCILER_01"
    action := actionModify
    reasonCode := some 1   -- TRANSCRIPTION_ERROR
    tsUnixMs := 1755400000900
    oldValueHash := "77ac319bfe1979e2d799d9e6987e65feb54f61511c03552ebae990826c208590"
    newValueHash := "004a9e0878ff83e6b91f50d50dad439d2065c6cbb0d20f1f328b2fd75e085d6a"
    sigOk := true }

/-- PROVED (S4-D-30 accepting case): an entry chained to the current head of
the real ledger fixture satisfies the bound. -/
example : AuditEntryValid validEntry ctx0 := by decide

/-- REFUTED: backdated — stamped exactly at the ledger head (strict `<` bites;
a replay of the head's own instant is not a successor). -/
example : ¬ AuditEntryValid { validEntry with tsUnixMs := 1755400000355 } ctx0 := by
  decide

/-- REFUTED: backdated — stamped before the ledger head. -/
example : ¬ AuditEntryValid { validEntry with tsUnixMs := 1755400000354 } ctx0 := by
  decide

/-- REFUTED: future-skewed — 1 ms past `nowMs + forwardSkewMs`. -/
example : ¬ AuditEntryValid { validEntry with tsUnixMs := 1755400006001 } ctx0 := by
  decide

/-- PROVED: future-dated exactly at the skew bound is still admissible (`≤`). -/
example : AuditEntryValid { validEntry with tsUnixMs := 1755400006000 } ctx0 := by
  decide

/-- REFUTED: invalid-sig — Ed25519 verification over the ledger-stored
canonical bytes failed upstream (`sigOk = false`). -/
example : ¬ AuditEntryValid { validEntry with sigOk := false } ctx0 := by decide

/-- REFUTED: missing-reason — the wire body carried no `reasonCode` field. -/
example : ¬ AuditEntryValid { validEntry with reasonCode := none } ctx0 := by decide

/-- REFUTED: unknown-reason-code — present but outside the enum
(`reasonCodeCount` is the first undefined index). -/
example : ¬ AuditEntryValid { validEntry with reasonCode := some reasonCodeCount } ctx0 := by
  decide

/-- REFUTED: actor missing. -/
example : ¬ AuditEntryValid { validEntry with actorId := "" } ctx0 := by decide

/-- REFUTED: a `modify` whose hashes are equal is not a modification. -/
example :
    ¬ AuditEntryValid
        { validEntry with newValueHash := validEntry.oldValueHash } ctx0 := by
  decide

/-- REFUTED: a `modify` with no prior value bound (`oldValueHash = ""`). -/
example : ¬ AuditEntryValid { validEntry with oldValueHash := "" } ctx0 := by decide

/-- REFUTED: action code outside the enum range. -/
example : ¬ AuditEntryValid { validEntry with action := actionCount } ctx0 := by decide

/-- PROVED: an `annotate` does not require the hashes to differ. -/
example :
    AuditEntryValid
      { validEntry with
          action := actionAnnotate
          newValueHash := validEntry.oldValueHash } ctx0 := by
  decide

/-! ### Ledger-head binding vectors (S4-D-30) -/

/-- REFUTED: stub context — an empty `ledgerHeadHash` is not a chain head. -/
example :
    ¬ AuditEntryValid validEntry
        { ctx0 with ledgerHeadHash := "" } := by decide

/-- REFUTED: stub context — a non-digest `ledgerHeadHash` (wrong length)
cannot pose as a chain head. -/
example :
    ¬ AuditEntryValid validEntry
        { ctx0 with ledgerHeadHash := "stub" } := by decide

/-- REFUTED: genesis head with a fabricated non-zero timestamp — an empty
chain has no entry to take a timestamp from. -/
example :
    ¬ AuditEntryValid validEntry
        { ctx0 with ledgerHeadHash := genesisHeadHash } := by decide

/-- REFUTED: real head hash with a zeroed timestamp — the classic
disable-the-backdating-check stub (`ledger_head_ts = 0` against a non-empty
chain) is refuted even though monotonicity alone would pass. -/
example :
    ¬ AuditEntryValid validEntry
        { ctx0 with ledgerHeadTsMs := 0 } := by decide

/-- PROVED: the legitimate empty chain — genesis sentinel with timestamp 0 —
admits a first entry (a `create`, no prior value). -/
example :
    AuditEntryValid
      { validEntry with
          action := actionCreate
          oldValueHash := "" }
      { ledgerHeadHash := genesisHeadHash
        ledgerHeadTsMs := 0
        nowMs := 1755400001000 } := by decide

/-! ### Axiom audit

`AuditEntryValid` and its `Decidable` instance must have ZERO axiom
dependencies (`#print axioms` output is checked by eye in the ticket's
audit checklist and stays in the build log — 'does not depend on any
axioms' for both). -/

#print axioms AuditEntryValid
#print axioms instDecidableAuditEntryValid

end PolicyEnv
