#!/usr/bin/env python3
"""S4-D-30 — audit-bound harness: real-ledger head binding + Ed25519 over
ledger-stored canonical bytes.

What this proves, end to end, against the golden fixture in
``scripts/fixtures/audit_ledger/`` (generated by the REAL biject-api chain
code via ``scripts/gen_audit_fixture.py``):

  1. **Byte-equality of the canonicalization.** This file reimplements
     biject-api ``backend/app/audit.py``'s canonical entry hash
     (sha256 over ``json.dumps(entry - {entry_hash, prev_hash, signature},
     sort_keys=True, separators=(",", ":"), default=str)``) and the compact
     line serialization. Both are checked byte-for-byte against every fixture
     line the real code wrote. When a biject-api checkout is importable, the
     live ``_canonical_entry_hash`` is additionally cross-called on every
     entry and must agree.

  2. **The ledger head is derived from the chain, not supplied.** The full
     chain is verified first — canonical-hash recompute, ``prev_hash``
     linkage from the 64-zero genesis sentinel, Ed25519 (ledger key) over
     ``entry_hash`` — then ``ledgerHeadTsMs`` is derived from the verified
     head entry's own contents as ``max(params.ts_unix_ms,
     timestamp_ns // 10**6)`` and cross-checked against the
     ``audit_head.json`` head pointer. Nothing here accepts a caller-
     supplied timestamp (the "stub" S4-D-30 retires).

  3. **sigOk is Ed25519 over the same canonical bytes the ledger stores.**
     For every fixture entry the agent-signature preimage
     ``actorId|action|itemOid|oldValueHash|newValueHash|reasonCode|tsUnixMs``
     is rebuilt from the params AS PERSISTED in the signed chain (the same
     bytes that feed ``entry_hash``), hashed, compared to the stored
     ``signed_digest``, and the agent's Ed25519 signature is verified over
     that digest's ASCII hex. A tampered param, digest, or signature flips
     the verdict — demonstrated by the negative checks.

  4. **The Lean accepting vector agrees with the real chain.** The literals
     in ``PolicyEnv/PolicyEnv/AuditBound.lean`` (the checked-in source of
     truth) are parsed out and compared against the values derived in 2–3,
     and the candidate entry is signed with a RUNTIME-EPHEMERAL agent key
     and verified, yielding ``sigOk = true`` for exactly the vector Lean
     proves.

Runtime dependency: ``cryptography`` only (see scripts/requirements.txt).
Keys: the fixture ships PUBLIC keys only; the candidate-signing key is
generated fresh per run and never persisted (Section 2B.3).

Usage:  python3 scripts/audit_bound_harness.py [--biject-api PATH]
Exit status 0 = every check passed; 1 = at least one failure.
"""

from __future__ import annotations

import argparse
import base64
import hashlib
import json
import re
import sys
from pathlib import Path

from cryptography.exceptions import InvalidSignature
from cryptography.hazmat.primitives.asymmetric.ed25519 import (
    Ed25519PrivateKey,
    Ed25519PublicKey,
)

REPO_ROOT = Path(__file__).resolve().parent.parent
FIXTURE_DIR = REPO_ROOT / "scripts" / "fixtures" / "audit_ledger"
AUDIT_BOUND_LEAN = REPO_ROOT / "PolicyEnv" / "PolicyEnv" / "AuditBound.lean"
CONTRACT_LEAN = REPO_ROOT / "PolicyEnv" / "PolicyEnv" / "Contract.lean"

GENESIS = "0" * 64
_HASH_EXCLUDE = {"entry_hash", "prev_hash", "signature"}

_failures: list[str] = []


def check(name: str, ok: bool, detail: str = "") -> None:
    print(f"  [{'PASS' if ok else 'FAIL'}] {name}" + (f" — {detail}" if detail else ""))
    if not ok:
        _failures.append(name)


# ── reimplementation of biject-api backend/app/audit.py canonical rules ──────


def canonical_entry_hash(d: dict) -> str:
    """Byte-identical reimplementation of audit._canonical_entry_hash."""
    payload = {k: v for k, v in d.items() if k not in _HASH_EXCLUDE}
    canonical = json.dumps(payload, sort_keys=True, separators=(",", ":"), default=str)
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


def serialize_line(d: dict) -> str:
    """Compact serialization matching the pydantic model_dump_json line format
    the real writer appends (ASCII fixture: no escaping differences)."""
    return json.dumps(d, separators=(",", ":"), ensure_ascii=False)


def sha256_hex(s: str) -> str:
    return hashlib.sha256(s.encode("utf-8")).hexdigest()


def signed_digest_from_params(p: dict) -> str:
    """Rebuild the agent-signature preimage digest from LEDGER-STORED params
    (mirrors biject-proxy extract.rs::signed_digest; action as this repo's
    integer enum — see .claude/deviations/S4-D-30.md)."""
    preimage = (
        f"{p['actor_id']}|{p['action']}|{p['item_oid']}|{p['old_value_hash']}"
        f"|{p['new_value_hash']}|{p['reason_code']}|{p['ts_unix_ms']}"
    )
    return sha256_hex(preimage)


def verify_ed25519(pub: Ed25519PublicKey, sig: bytes, msg: bytes) -> bool:
    try:
        pub.verify(sig, msg)
        return True
    except InvalidSignature:
        return False


# ── checks ───────────────────────────────────────────────────────────────────


def load_fixture() -> tuple[list[str], list[dict], Ed25519PublicKey, Ed25519PublicKey]:
    lines = [
        ln for ln in (FIXTURE_DIR / "audit.log").read_text().splitlines() if ln.strip()
    ]
    entries = [json.loads(ln) for ln in lines]
    ledger_pub = Ed25519PublicKey.from_public_bytes(
        bytes.fromhex((FIXTURE_DIR / "ledger_public_key.hex").read_text().strip())
    )
    agent_pub = Ed25519PublicKey.from_public_bytes(
        bytes.fromhex((FIXTURE_DIR / "agent_public_key.hex").read_text().strip())
    )
    return lines, entries, ledger_pub, agent_pub


def check_byte_equality(lines: list[str], entries: list[dict], api_path: Path) -> None:
    print("\n[1] canonicalization byte-equality vs the real-rules fixture")
    for i, (ln, e) in enumerate(zip(lines, entries)):
        check(
            f"entry {i}: line re-serializes byte-identically",
            serialize_line(e) == ln,
        )
        check(
            f"entry {i}: reimplemented canonical hash == stored entry_hash",
            canonical_entry_hash(e) == e["entry_hash"],
            e["entry_hash"][:16] + "…",
        )

    # Optional live cross-check against the real audit.py, when importable.
    audit_py = api_path / "backend" / "app" / "audit.py"
    if audit_py.exists():
        try:
            import os

            os.environ.setdefault(
                "AUDIT_SIGNING_KEY", base64.b64encode(os.urandom(32)).decode()
            )
            sys.path.insert(0, str(api_path / "backend"))
            from app.audit import _canonical_entry_hash as live_hash  # noqa: E402

            agree = all(live_hash(e) == canonical_entry_hash(e) for e in entries)
            check("live cross-check vs biject-api audit._canonical_entry_hash", agree)
        except Exception as exc:  # missing deps → skip, not a failure
            print(f"  [SKIP] live cross-check (biject-api import failed: {type(exc).__name__})")
    else:
        print("  [SKIP] live cross-check (no biject-api checkout found)")


def verify_chain_and_derive_head(
    entries: list[dict], ledger_pub: Ed25519PublicKey
) -> tuple[str, int]:
    print("\n[2] full chain verification + head derivation (the real head, no stub)")
    prev = GENESIS
    ok_chain = True
    for i, e in enumerate(entries):
        if canonical_entry_hash(e) != e["entry_hash"]:
            ok_chain = False
            check(f"entry {i}: content integrity", False)
        if e["prev_hash"] != prev:
            ok_chain = False
            check(f"entry {i}: prev_hash linkage", False)
        if not verify_ed25519(
            ledger_pub, bytes.fromhex(e["signature"]), e["entry_hash"].encode()
        ):
            ok_chain = False
            check(f"entry {i}: ledger Ed25519 over entry_hash", False)
        prev = e["entry_hash"]
    check(
        "chain verifies (canonical hash + genesis linkage + Ed25519 over entry_hash)",
        ok_chain,
        f"{len(entries)} entries from genesis {GENESIS[:8]}…",
    )

    head = entries[-1]
    head_hash = head["entry_hash"]
    ptr = json.loads((FIXTURE_DIR / "audit_head.json").read_text())
    check(
        "audit_head.json pointer cross-check",
        ptr["chain_head_hash"] == head_hash and ptr["entry_count"] == len(entries),
        f"head={ptr['chain_head_hash'][:16]}… count={ptr['entry_count']}",
    )

    head_ts = max(head["params"]["ts_unix_ms"], head["timestamp_ns"] // 1_000_000)
    print(
        f"  derived ledgerHeadTsMs = {head_ts} "
        f"(= max(params.ts_unix_ms={head['params']['ts_unix_ms']}, "
        f"timestamp_ns//1e6={head['timestamp_ns'] // 1_000_000}))"
    )
    print(f"  derived ledgerHeadHash = {head_hash}")
    return head_hash, head_ts


def check_agent_signatures(entries: list[dict], agent_pub: Ed25519PublicKey) -> None:
    print("\n[3] Ed25519 (sigOk) over the canonical bytes the ledger stores")
    for i, e in enumerate(entries):
        p = e["params"]
        digest = signed_digest_from_params(p)
        check(
            f"entry {i}: signed_digest recomputed from LEDGER-STORED params matches",
            digest == p["signed_digest"],
        )
        sig_ok = verify_ed25519(
            agent_pub, base64.b64decode(p["sig_ed25519"]), digest.encode("ascii")
        )
        check(f"entry {i}: agent Ed25519 over recomputed digest -> sigOk", sig_ok)

    # Negative checks: any divergence between proven and recorded bytes flips sigOk.
    head = entries[-1]
    tampered = dict(head["params"])
    tampered["new_value_hash"] = sha256_hex("6.66")
    check(
        "tampered stored param -> recomputed digest no longer matches (sigOk pipeline denies)",
        signed_digest_from_params(tampered) != head["params"]["signed_digest"],
    )
    check(
        "tampered stored param -> ledger entry_hash mismatch (chain verification denies)",
        canonical_entry_hash({**head, "params": tampered}) != head["entry_hash"],
    )
    bad_sig = bytearray(base64.b64decode(head["params"]["sig_ed25519"]))
    bad_sig[0] ^= 0xFF
    check(
        "flipped signature byte -> sigOk = False",
        not verify_ed25519(
            agent_pub, bytes(bad_sig), head["params"]["signed_digest"].encode()
        ),
    )


def parse_lean_vector() -> dict:
    """Extract the accepting-vector literals from the checked-in Lean source
    of truth (AuditBound.lean ctx0/validEntry + Contract.lean constants)."""
    lean = AUDIT_BOUND_LEAN.read_text()
    contract = CONTRACT_LEAN.read_text()

    def block(name: str) -> str:
        m = re.search(rf"private def {name}[^{{]*\{{(.*?)\}}", lean, re.S)
        if not m:
            raise SystemExit(f"FATAL: could not find `{name}` in AuditBound.lean")
        return m.group(1)

    head_hash = re.search(
        r'private def fixtureHeadHash : String :=\s*"([0-9a-f]{64})"', lean
    ).group(1)
    ctx, entry = block("ctx0"), block("validEntry")
    grab = lambda blk, field, pat: re.search(rf"{field} :=\s*{pat}", blk).group(1)
    return {
        "fixtureHeadHash": head_hash,
        "ledgerHeadTsMs": int(grab(ctx, "ledgerHeadTsMs", r"(\d+)")),
        "nowMs": int(grab(ctx, "nowMs", r"(\d+)")),
        "tsUnixMs": int(grab(entry, "tsUnixMs", r"(\d+)")),
        "oldValueHash": grab(entry, "oldValueHash", r'"([0-9a-f]{64})"'),
        "newValueHash": grab(entry, "newValueHash", r'"([0-9a-f]{64})"'),
        "reasonCode": int(grab(entry, "reasonCode", r"some (\d+)")),
        "actorId": grab(entry, "actorId", r'"([^"]+)"'),
        "itemOid": grab(entry, "itemOid", r'"([^"]+)"'),
        "forwardSkewMs": int(
            re.search(r"def forwardSkewMs : Nat := (\d+)", contract).group(1)
        ),
        "genesisHeadHash": re.search(
            r'def genesisHeadHash : String :=\s*"(0{64})"', contract
        ).group(1),
    }


def check_lean_agreement(
    vec: dict, head_hash: str, head_ts: int, entries: list[dict]
) -> None:
    print("\n[4] agreement: Lean accepting vector <-> real chain fixture head")
    head = entries[-1]
    check(
        "Lean fixtureHeadHash == verified chain head entry_hash",
        vec["fixtureHeadHash"] == head_hash,
    )
    check(
        "Lean ctx0.ledgerHeadTsMs == chain-derived head timestamp",
        vec["ledgerHeadTsMs"] == head_ts,
        str(head_ts),
    )
    check(
        "Lean validEntry.oldValueHash == head entry's ledger-stored new_value_hash",
        vec["oldValueHash"] == head["params"]["new_value_hash"],
    )
    check(
        "Lean genesisHeadHash == audit.py GENESIS sentinel (64 hex zeros)",
        vec["genesisHeadHash"] == GENESIS,
    )
    check(
        "Lean forwardSkewMs == proxy AUDIT_SKEW_MS default (5000 ms)",
        vec["forwardSkewMs"] == 5000,
    )
    check(
        "vector arithmetic: headTs < tsUnixMs <= nowMs + forwardSkewMs",
        head_ts < vec["tsUnixMs"] <= vec["nowMs"] + vec["forwardSkewMs"],
        f"{head_ts} < {vec['tsUnixMs']} <= {vec['nowMs'] + vec['forwardSkewMs']}",
    )

    # sigOk for the accepting vector: sign the candidate's canonical preimage
    # with a runtime-ephemeral agent key (never persisted) and verify.
    key = Ed25519PrivateKey.generate()
    candidate_params = {
        "actor_id": vec["actorId"],
        "action": 1,  # actionModify
        "item_oid": vec["itemOid"],
        "old_value_hash": vec["oldValueHash"],
        "new_value_hash": vec["newValueHash"],
        "reason_code": vec["reasonCode"],
        "ts_unix_ms": vec["tsUnixMs"],
    }
    digest = signed_digest_from_params(candidate_params)
    sig = key.sign(digest.encode("ascii"))
    check(
        "candidate entry signed (ephemeral key) and verified -> sigOk = true",
        verify_ed25519(key.public_key(), sig, digest.encode("ascii")),
        f"signed_digest={digest[:16]}…",
    )
    print(
        "  accepting vector (Lean is source of truth): "
        + json.dumps(
            {k: vec[k] for k in ("ledgerHeadTsMs", "tsUnixMs", "nowMs", "reasonCode")}
        )
    )


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--biject-api", default=str(REPO_ROOT.parent / "biject-api"))
    args = ap.parse_args()

    print("S4-D-30 audit-bound harness")
    print(f"fixture: {FIXTURE_DIR.relative_to(REPO_ROOT)}")

    lines, entries, ledger_pub, agent_pub = load_fixture()
    check_byte_equality(lines, entries, Path(args.biject_api))
    head_hash, head_ts = verify_chain_and_derive_head(entries, ledger_pub)
    check_agent_signatures(entries, agent_pub)
    vec = parse_lean_vector()
    check_lean_agreement(vec, head_hash, head_ts, entries)

    print()
    if _failures:
        print(f"RESULT: FAIL ({len(_failures)} failed): {_failures}")
        return 1
    print("RESULT: PASS — all checks green")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
